### ISSUE TITLE
Missing file when running program

### ISSUE THREAD

**Issue by BrandenEK** [BrandenEK/Windwaker-coop#1]
Leaving through the door on the pirate ship after someone enters the Forsaken Fortress spawns you on Windfall Island at night

**Comment by BrandenEK** [comment]
In Forest Haven, obtaining the Deku Leaf starts a cutscene that will softlock others if they are in a certain animation (grappling)

**Comment by silveraegis39** [comment]
is there a way to test this build?

**Comment by BrandenEK** [comment]
@silveraegis39   The most recent release, titled 'Command Loop' should work.  Just make sure that you are using Dolphin 5.0 and all your computers are on the same local network.  I haven't tested the game to full completion yet, but it syncs most forms of progress so it should be completable.  If you run into any issues or something doesn't work right, please let me know!

**Comment by silveraegis39** [comment]
Is there any executable files? Because i don't see any releases except the source code. Also, when you say local network, would using Hamachi work?

**Comment by BrandenEK** [comment]
@silveraegis39  Yes there should be a zip file in the assets that contains the executable.  I haven't tested it using Hamachi, but it should theoretically work.

**Comment by silveraegis39** [comment]
Tried to run the latest build and nothing happens. Deactivated anti-virus, ran as admin, ran it with the compatibility of every windows releases and it still won't open. Do we need something special to run it? Because right now its appears for 0.5 second on my taskbar then nothing happens after.

**Comment by BrandenEK** [comment]
You shouldn't need anything extra to run it, as long as you're on windows.  Unfortunately, that is the same problem that I experienced a lot when testing it on different devices.  Can you run the program from command line so that the error screen stays up and you can see the exact error?

**Comment by BrandenEK** [comment]
@silveraegis39  open command prompt and navigate to the folder, then type just the name of the exe file and it should be running the program in the same console window.

**Comment by silveraegis39** [comment]
missing a file it seem
![Crash log](https://user-images.githubusercontent.com/32630708/148452446-d8179501-0061-4e07-9854-eb8c7575f012.PNG)
s

**Comment by BrandenEK** [comment]
@silveraegis39 Sorry, I wasn't very clear, did you type "windwaker-coop.exe"?

**Comment by silveraegis39** [comment]
I typed .exe many times and it just did the same as without command prompt so i typed it without the extension. I guess we won't know what my problem is if it's not this.

**Comment by BrandenEK** [comment]
@silveraegis39  Interesting.  Then that first image you attached was probably correct and you are missing certain .net runtime files.  Try downloading .NET 5.0 from here: https://dotnet.microsoft.com/en-us/download/dotnet.  After installing this, the program should hopefully work.

**Comment by silveraegis39** [comment]
Alright i'll give it a try when i have access to my computer! Thank you for your help, really appreciated!

**Comment by silveraegis39** [comment]
I just tried installing it and it still does the same thing. no idea what i could be missing else.

**Comment by silveraegis39** [comment]
I just fixed the problem! i needed to install .NET 3.1.0. Now it opens and i get command prompt to write the host name!
Thank you very much for your patience and for your efforts on this coop mod!

**Comment by BrandenEK** [comment]
@silveraegis39  That is great!  Thank you so much for taking an interest in this and bringing this problem to my attention.  The current version should work how it is, but I will definitely be working on this more and a new and improved version should be coming out soon.
