### ISSUE TITLE
Feature Request for WW Randomizer

### ISSUE THREAD

**Issue by Ehkad** [BrandenEK/Windwaker-coop#33]
I love this project! My girlfriend and I have been using it to do Wind Waker Randomizers together. I was just curious about maybe adding the tinkle gold statues from the randomizer to the list of items that can get synchronized by the server. I understand that this may not be something that the project aims to achieve but, I just think it would be super awesome! Thank you for all the work done on this project. Again I love this project.

**Comment by BrandenEK** [comment]
That is amazing to hear!  I am a big fan of randomizers, and I had hoped that this project would support randomizer, though I haven't actually tested it yet.  Does it work well with randomizer?  With regards to the tingle statues, that is a great idea to have them synced also.  I don't know if it will be anytime soon, as I haven't worked on this project in a while, but I will definitely keep it in mind.
