### ISSUE TITLE
help wanted with item code for 'give' command

### ISSUE THREAD

**Issue by MythicInc** [BrandenEK/Windwaker-coop#34]
How do you use the 'give' command? I've recently started a shared randomizer for WW and we softlocked ourselves because the Tingle statues don't sync, but their respective chests have already been opened for both of us.

**Comment by BrandenEK** [comment]
The give command works by typing "give NAME [AMOUNT]", and the item names can be found at the bottom of https://github.com/BrandenEK/Windwaker-coop/blob/main/Windwaker-coop/Games/Windwaker.cs.

Unfortunately, tingle statues don't sync yet, so there is no way to use the give command for them.  When I come back to this project however, that is going to be one of my first priorities.

Very sorry about that.

**Comment by BrandenEK** [comment]
Tingle statues now sync between players in the new 0.7.4 release.
