### ISSUE TITLE
Progress does not sync and cheats do not work

### ISSUE THREAD

**Issue by johnBrink** [BrandenEK/Windwaker-coop#38]
Hello, sorry for the trouble! I can't tell if I'm doing something wrong, but the app isn't doing anything for me.

I have tested on the following versions of Dolphin:

* 5.0-21088
* 5.0-21460 (latest 5.0)

My server and one of the clients run on the same machine. I have tried running a second client on another computer, and I have also tried running both clients (along with the server) on the same computer.

After connecting my 2 clients to the server, I get messages like "[player name] has joined/left the game!", and when I try to use the "give" command, I get messages like "Cheat activated!" and "[player name] used a cheat!". However, none of this has any effect in-game. Also, when I collect items legitimately (such as the hero's clothes at the very beginning), I don't even get a message for it in any of my consoles, nor do I see the clothes appear on the second player's session.

It seems as if the game is not properly reading/writing to Dolphin's memory. Am I supposed to be using a different version of Dolphin besides these recent 5.0 builds?

I'm on Windows x64, and the latest 0.7.4 of your app BTW.

Edit: I also forgot to mention, I'm running the European version of the game. Does this app only work with the NTSC version?

**Comment by BrandenEK** [comment]
It is only guaranteed to work on the legacy 5.0 of dolphin (Released 8 or 9 years ago). It might work on more recent versions but I am not sure. 

You also mention NTSC. It most likely will not work on the European version.

Hopefully this helps, let me know if it works now.

**Comment by johnBrink** [comment]
Okay, thanks for confirming! I was hoping to transition a save file from the multiplayer mod (which only supports PAL), so I'm not sure how worth it this will be. I'll try ripping my NTSC disc and see if that helps.

**Comment by johnBrink** [comment]
Sadly, I was unable to rip my disc so I am unable to verify functionality on the NTSC version. I'll just take your word for it and go back to playing that one WW Multiplayer mod. Thanks for responding, though!
